# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "video-torrent-info"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pavel Tatarsky"]
  s.date = "2013-12-09"
  s.description = "It simply loads small part of torrent that contains metadata and processes it with ffmpeg"
  s.email = "fazzzenda@mail.ru"
  s.extensions = ["ext/torrent_client/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/torrent_client.bundle",
    "lib/video_torrent_info.rb",
    "spec/fixtures/test.torrent",
    "spec/lib/torrent_client_spec.rb",
    "spec/lib/video_torrent_info_spec.rb",
    "spec/spec_helper.rb",
    "video-torrent-info.gemspec"
  ]
  s.homepage = "http://github.com/vintikzzz/video-torrent-info"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.5"
  s.summary = "Gets video info for the torrent file"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rake-compiler>, [">= 0"])
      s.add_development_dependency(%q<rice>, [">= 0"])
      s.add_development_dependency(%q<ffmpeg-video-info>, [">= 0"])
      s.add_development_dependency(%q<bencode>, [">= 0"])
      s.add_runtime_dependency(%q<ffmpeg-video-info>, [">= 0"])
      s.add_runtime_dependency(%q<rice>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
      s.add_dependency(%q<rice>, [">= 0"])
      s.add_dependency(%q<ffmpeg-video-info>, [">= 0"])
      s.add_dependency(%q<bencode>, [">= 0"])
      s.add_dependency(%q<ffmpeg-video-info>, [">= 0"])
      s.add_dependency(%q<rice>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
    s.add_dependency(%q<rice>, [">= 0"])
    s.add_dependency(%q<ffmpeg-video-info>, [">= 0"])
    s.add_dependency(%q<bencode>, [">= 0"])
    s.add_dependency(%q<ffmpeg-video-info>, [">= 0"])
    s.add_dependency(%q<rice>, [">= 0"])
  end
end

