# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: video-torrent-info 0.1.20 ruby lib
# stub: ext/torrent_client/extconf.rb

Gem::Specification.new do |s|
  s.name = "video-torrent-info"
  s.version = "0.1.20"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Pavel Tatarsky"]
  s.date = "2016-01-27"
  s.description = "It simply loads small part of torrent that contains metadata and processes it with ffmpeg"
  s.email = "fazzzenda@mail.ru"
  s.extensions = ["ext/torrent_client/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/torrent_client/extconf.rb",
    "ext/torrent_client/torrent_client.cpp",
    "lib/video_torrent_info.rb",
    "spec/fixtures/test.torrent",
    "spec/fixtures/test2.torrent",
    "spec/fixtures/test3.torrent",
    "spec/lib/torrent_client_spec.rb",
    "spec/lib/video_torrent_info_spec.rb",
    "spec/spec_helper.rb",
    "video-torrent-info.gemspec"
  ]
  s.homepage = "http://github.com/vintikzzz/video-torrent-info"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.7"
  s.summary = "Gets video info for the torrent file"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rake-compiler>, [">= 0"])
      s.add_development_dependency(%q<bencode>, [">= 0"])
      s.add_runtime_dependency(%q<ffmpeg-video-info>, [">= 0"])
      s.add_runtime_dependency(%q<rice>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
      s.add_dependency(%q<bencode>, [">= 0"])
      s.add_dependency(%q<ffmpeg-video-info>, [">= 0"])
      s.add_dependency(%q<rice>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
    s.add_dependency(%q<bencode>, [">= 0"])
    s.add_dependency(%q<ffmpeg-video-info>, [">= 0"])
    s.add_dependency(%q<rice>, [">= 0"])
  end
end

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'ffmpeg_video_info/version'

Gem::Specification.new do |s|
  s.name          = "video-torrent-info"
  s.version       = VideoTorrentInfo::VERSION
  s.authors       = ["Pavel Tatarsky"]
  s.email         = ["fazzzenda@mail.ru"]
  s.summary       = "Gets video info for the torrent file"
  s.extensions    = ["ext/ffmpeg_video_info_ext/extconf.rb"]
  s.homepage      = "http://github.com/vintikzzz/video-torrent-info"
  s.license       = "MIT"

  s.required_ruby_version = '>= 1.9.3'

  s.files         = `git ls-files -z`.split("\x0")
  s.executables   = s.files.grep(%r{^bin/}) { |f| File.basename(f) }
  s.test_files    = s.files.grep(%r{^(test|spec|features)/})
  s.require_paths = ["lib"]

  s.add_dependency 'ffmpeg-video-info'
  s.add_dependency 'bencode'

  s.add_development_dependency 'rdoc'
  s.add_development_dependency 'rake'
  s.add_development_dependency 'bundler'
  s.add_development_dependency 'rspec'
  s.add_development_dependency 'rake-compiler'
  s.add_development_dependency 'rice'

end
